//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bets
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BetsEntities : DbContext
    {
        public BetsEntities()
            : base("name=BetsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GlobalBet> GlobalBets { get; set; }
        public virtual DbSet<GoalscorersForRound> GoalscorersForRounds { get; set; }
        public virtual DbSet<MatchBet> MatchBets { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PointsForRound> PointsForRounds { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
