//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bets
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalBet
    {
        public int BetID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> WinnerTeamID { get; set; }
        public Nullable<int> GoalscorerID { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
