//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bets
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalscorersForRound
    {
        public int RoundID { get; set; }
        public int GoalscorerID { get; set; }
        public int Goals { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Round Round { get; set; }
    }
}
