//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.MatchBets = new HashSet<MatchBet>();
        }
    
        public int MatchID { get; set; }
        public int FirstTeamID { get; set; }
        public int SecondTeamID { get; set; }
        public System.DateTime Date { get; set; }
        public int Points1 { get; set; }
        public Nullable<int> PointsX { get; set; }
        public int Points2 { get; set; }
        public int RoundID { get; set; }
        public Nullable<int> FirstTeamGoals { get; set; }
        public Nullable<int> SecondTeamGoals { get; set; }
        public Nullable<int> Result { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Round Round { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchBet> MatchBets { get; set; }
    }
}
