//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bets
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchBet
    {
        public int BetID { get; set; }
        public int MatchID { get; set; }
        public int UserID { get; set; }
        public int FirstTeamGoals { get; set; }
        public int SecondTeamGoals { get; set; }
        public int Result { get; set; }
        public int PointsWon { get; set; }
        public int PointsWonBonus { get; set; }
        public int WinTypeID { get; set; }
        public int Bonus { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Match Match { get; set; }
    }
}
