//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.GlobalBets = new HashSet<GlobalBet>();
            this.GoalscorersForRounds = new HashSet<GoalscorersForRound>();
        }
    
        public int PlayerID { get; set; }
        public int TeamID { get; set; }
        public string Name { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public bool Active { get; set; }
        public int Points { get; set; }
        public int GoalsScored { get; set; }
        public string ExternalID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlobalBet> GlobalBets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoalscorersForRound> GoalscorersForRounds { get; set; }
    }
}
