//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bets
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointsForRound
    {
        public int UserID { get; set; }
        public int RoundID { get; set; }
        public int MatchPoints { get; set; }
        public int MatchPointsBonus { get; set; }
        public int GoalscorerPoints { get; set; }
    
        public virtual Round Round { get; set; }
        public virtual User User { get; set; }
    }
}
