//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingID { get; set; }
        public int CurrentRoundID { get; set; }
        public System.DateTime FirstMatchDate { get; set; }
        public double ScoreMultiplier { get; set; }
        public double RoundGoalMultiplier { get; set; }
        public double BonusMultiplier { get; set; }
        public Nullable<int> LastNotificationRoundID { get; set; }
        public Nullable<int> MaxBonusPerMatch { get; set; }
    
        public virtual Round Round { get; set; }
    }
}
